name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: android-app
      run: ./gradlew build
    - name: Get Keystore
      working-directory: android-app
      run: echo ${{ secrets.keystore }} | base64 --decode > keystore.jks
    - name: Create APK
      working-directory: android-app
      run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=keystore.jks -Pandroid.injected.signing.store.password=${{ secrets.keystore_password }} -Pandroid.injected.signing.key.alias=key0 -Pandroid.injected.signing.key.password=${{ secrets.key0_password }}
