name: Android APK

on:
  push:
    branches:
      - master

jobs:
  build-and-create-apk:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Test with Gradle
      working-directory: android-app
      run: chmod +x ./gradlew && ./gradlew build
    - name: Get Keystore
      working-directory: android-app
      env:
        KEYSTORE_CONTENTS: ${{ secrets.keystore }}
      run: |
        echo $KEYSTORE_CONTENTS | base64 --decode > keystore.jks
    - name: Create APK
      working-directory: android-app
      env:
        STORE_PASSWORD: ${{ secrets.keystore_password }}
        KEY_ALIAS: ${{ secrets.key_alias }}
        ALIAS_PASSWORD: ${{ secrets.alias_password }}
      run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$PWD/keystore.jks -Pandroid.injected.signing.store.password=$STORE_PASSWORD -Pandroid.injected.signing.key.alias=$KEY_ALIAS -Pandroid.injected.signing.key.password=$ALIAS_PASSWORD
    - name: Upload APK
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cash-calculator.apk
        # Directory containing files to upload
        path: ./android-app/app/build/outputs/apk/release/app-release.apk
