name: Push Javadoc

on:
  push:
    branches:
      - document-setup

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate javadoc with Gradle
        working-directory: android-app
        run: chmod +x ./gradlew && ./gradlew build
      - name: Commit javadoc files
        run: |
          git config --global user.name 'ajyang2000'
          git config --global user.email 'alexander_yang_12@hotmail.com'
          git commit -am "Automated javadoc"
          git push origin document-setup